version: "3.8"
services:
  backend_server:
    build:
      context: ..
      dockerfile: stt_dev/Dockerfile
    command: ["/run_server.sh", "stt_dev.backend_server.server", "8000"]
    volumes:
      - ..:/app
      - ./stt_server/whisper_model:/app/stt_dev/stt_server/whisper_model
    environment:
      - HOT_RELOAD
    ports:
      - "8000:8000"
  stt_server:
    build:
      context: ..
      dockerfile: stt_dev/Dockerfile
    command: ["/run_server.sh", "stt_dev.stt_server.server", "8001"]
    volumes:
      - ..:/app
      - ./stt_server/whisper_model:/app/stt_dev/stt_server/whisper_model
    environment:
      - HOT_RELOAD
    ports:
      - "8001:8001"
  telegram_server:
    build:
      context: ..
      dockerfile: stt_dev/Dockerfile
    command: python -m stt_dev.telegram_server.server
    volumes:
      - ..:/app
    environment:
      - HOT_RELOAD
